//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Week13.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_product
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
